% Andrew Stannard
clear variables; close all;

CBP = [0 114 187; 241 90 35; 0 168 117; 235 222 58; ...
    219 111 171; 248 147 29; 1 186 242; 189 190 192]/255;

apA_wo = [1.30 4.11 -0.07 -1.22 1.34]';
apB_wo = [0.60 -1.06 1.48 -2.32 -3.11]';
rA_wo = [1.32 2.50 0.77 -1.48 3.63]';
rB_wo = [1.89 -0.13 -1.95 -2.67 3.43]';
pA_wo = [-0.77 1.22 2.06 -4.16 -2.33]';
pB_wo = [-1.33 -0.18 2.05 1.42 1.99]';
control_wo = [-1.59 2.55 2.23 -1.33 -2.57]';

apA_w = [30.41 29.45 26.91 25.25 22.54]';
apB_w = [21.01 20.56 28.58 19.66 18.03]';
rA_w = [20.68 27.02 30.23 24.38 12.76]';
rB_w = [18.55 15.06 29.63 20.82 23.61]';
pA_w = [ 36.24 44.76 44.41 44.89 28.04]';
pB_w = [26.51 31.11 42.84 47.71 44.51]';
control_w = [36.15 49.38 33.05 36.20 34.76]';

h = bar([mean([apA_wo apA_w]); mean([apB_wo apB_w]); ...
    mean([rA_wo rA_w]); mean([rB_wo rB_w]); mean([pA_wo pA_w]); ...
    mean([pB_wo pB_w]); mean([control_wo control_w])]');

set(gca, 'FontSize', 12, 'box', 'off'); hold on;

h(1).FaceColor = CBP(2,:);
errorbar(h(1).XEndPoints, mean([apA_wo apA_w]), ...
    std([apA_wo apA_w])/sqrt(length(apA_wo)-1), ...
    'LineStyle', 'none', 'Color', 'k', 'CapSize', 12);
scatter(repmat(h(1).XEndPoints(1), length(apA_wo), 1), apA_wo, 60, '<', ...
    'MarkerFaceColor', CBP(2,:), 'MarkerEdgeColor', 'k', ...
    'XJitter','randn','XJitterWidth', 0.1);
scatter(repmat(h(1).XEndPoints(2), length(apA_wo), 1), apA_w, 60, '<', ...
    'MarkerFaceColor', CBP(2,:), 'MarkerEdgeColor', 'k', ...
    'XJitter','randn','XJitterWidth', 0.1);

h(2).FaceColor = CBP(1,:);
errorbar(h(2).XEndPoints, mean([apB_wo apB_w]), ...
    std([apB_wo apB_w])/sqrt(length(apB_wo)-1), ...
    'LineStyle', 'none', 'Color', 'k', 'CapSize', 12);
scatter(repmat(h(2).XEndPoints(1), length(apB_wo), 1), apB_wo, 60, '>', ...
    'MarkerFaceColor', CBP(1,:), 'MarkerEdgeColor', 'k', ...
    'XJitter','randn','XJitterWidth', 0.1);
scatter(repmat(h(2).XEndPoints(2), length(apB_w), 1), apB_w, 60, '>', ...
    'MarkerFaceColor', CBP(1,:), 'MarkerEdgeColor', 'k', ...
    'XJitter','randn','XJitterWidth', 0.1);

h(3).FaceColor = CBP(3,:);
errorbar(h(3).XEndPoints, mean([rA_wo rA_w]), ...
    std([rA_wo rA_w])/sqrt(length(rA_wo)-1), ...
    'LineStyle', 'none', 'Color', 'k', 'CapSize', 12);
scatter(repmat(h(3).XEndPoints(1), length(rA_wo), 1), rA_wo, 60, '^', ...
    'MarkerFaceColor', CBP(3,:), 'MarkerEdgeColor', 'k', ...
    'XJitter','randn','XJitterWidth', 0.1);
scatter(repmat(h(3).XEndPoints(2), length(rA_w), 1), rA_w, 60, '^', ...
    'MarkerFaceColor', CBP(3,:), 'MarkerEdgeColor', 'k', ...
    'XJitter','randn','XJitterWidth', 0.1);

h(4).FaceColor = CBP(4,:);
errorbar(h(4).XEndPoints, mean([rB_wo rB_w]), ...
    std([rB_wo rB_w])/sqrt(length(rB_wo)-1), ...
    'LineStyle', 'none', 'Color', 'k', 'CapSize', 12);
scatter(repmat(h(4).XEndPoints(1), length(rB_wo), 1), rB_wo, 60, 'v', ...
    'MarkerFaceColor', CBP(4,:), 'MarkerEdgeColor', 'k', ...
    'XJitter','randn','XJitterWidth', 0.1);
scatter(repmat(h(4).XEndPoints(2), length(rB_w), 1), rB_w, 60, 'v', ...
    'MarkerFaceColor', CBP(4,:), 'MarkerEdgeColor', 'k', ...
    'XJitter','randn','XJitterWidth', 0.1);

h(5).FaceColor = CBP(7,:);
errorbar(h(5).XEndPoints, mean([pA_wo pA_w]), ...
    std([pA_wo pA_w])/sqrt(length(pA_wo)-1), ...
    'LineStyle', 'none', 'Color', 'k', 'CapSize', 12);
scatter(repmat(h(5).XEndPoints(1), length(pA_wo), 1), pA_wo, 60, 's', ...
    'MarkerFaceColor', CBP(7,:), 'MarkerEdgeColor', 'k', ...
    'XJitter','randn','XJitterWidth', 0.1);
scatter(repmat(h(5).XEndPoints(2), length(pA_w), 1), pA_w, 60, 's', ...
    'MarkerFaceColor', CBP(7,:), 'MarkerEdgeColor', 'k', ...
    'XJitter','randn','XJitterWidth', 0.1);

h(6).FaceColor = CBP(6,:);
errorbar(h(6).XEndPoints, mean([pB_wo pB_w]), ...
    std([pB_wo pB_w])/sqrt(length(pB_wo)-1), ...
    'LineStyle', 'none', 'Color', 'k', 'CapSize', 12);
scatter(repmat(h(6).XEndPoints(1), length(pB_wo), 1), pB_wo, 60, 'd', ...
    'MarkerFaceColor', CBP(6,:), 'MarkerEdgeColor', 'k', ...
    'XJitter','randn','XJitterWidth', 0.1);
scatter(repmat(h(6).XEndPoints(2), length(pB_w), 1), pB_w, 60, 'd', ...
    'MarkerFaceColor', CBP(6,:), 'MarkerEdgeColor', 'k', ...
    'XJitter','randn','XJitterWidth', 0.1);

h(7).FaceColor = CBP(5,:);
errorbar(h(7).XEndPoints, mean([control_wo control_w]), ...
    std([control_wo control_w])/sqrt(length(control_wo)-1), ...
    'LineStyle', 'none', 'Color', 'k', 'CapSize', 12);
scatter(repmat(h(7).XEndPoints(1), length(control_wo), 1), control_wo, ...
    60, 'o', 'MarkerFaceColor', CBP(5,:), 'MarkerEdgeColor', 'k', ...
    'XJitter','randn','XJitterWidth', 0.1);
scatter(repmat(h(7).XEndPoints(2), length(control_w), 1), control_w, ...
    60, 'o', 'MarkerFaceColor', CBP(5,:), 'MarkerEdgeColor', 'k', ...
    'XJitter','randn','XJitterWidth', 0.1);

xticklabels(["Control (0 mM Mg^{2+})" "Test (100 mM Mg^{2+})"]);
ylabel('Average FRET efficiency, \langleE\rangle (%)');
ylim([-6 60])